version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: root
      DB_PASSWORD: ${DB_PASS}
      DB_DATABASE: sword_health_sql

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: sword_health_sql
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

networks:
  default:
    driver: bridge
